on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]
  schedule:
    - cron: '0 6 * * *'

jobs:
  update-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install follow-redirects
      - uses: actions/github-script@v6
        with:
          script: |
            const crystal_nightly = require('./.github/update_nightly.js');
            const vs_hash = require('./.github/update_vs.js');
            await crystal_nightly({github, core});
            await vs_hash();

      - run: git diff --exit-code || git -c user.email='github-actions[bot]@users.noreply.github.com' -c user.name='github-actions[bot]' commit -a -m 'Update nightly version'
      - run: git push
